### ISSUE TITLE
New benchmark for different record batch sizes

### ISSUE THREAD

**Issue by jonkeane** [ursacomputing/arrowbench#74]
There are a few places we should do this:

* reads from disk using Datasets (save parquets with varying row_group sizes, and see what the performance is. Prior art and hypotheses: https://lists.apache.org/thread/xt9z12bjkm7czvv38q993czd80bdgrlc
* Across the C-Data stream (to answer questions like: https://github.com/duckdb/duckdb/issues/3138)

**Comment by alistaire47** [comment]
Closed via #87
